spring.application.name=volunteer

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=volunteer;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=User12345678
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.show-sql=true

## JWT
#app.jwtSecret=YourJWTSecretKeyHere
#app.jwtExpirationMs=86400000
#app.jwtRefreshExpirationMs=604800000
#
volunteerhub.jwtSecret=Aj32$ds!98sDf9zXDFd2k3F9sd3FAj32$ds!98sDf9zXDFd2k3F9sd3FAj32$ds!98sDf9zXDFd2k3F9sd3F
volunteerhub.jwtExpirationMs=86400000
volunteerhub.jwtRefreshExpirationMs=604800000

## Email (SMTP)
#spring.mail.host=smtp.example.com
#spring.mail.port=587
#spring.mail.username=your_email@example.com
#spring.mail.password=your_email_password
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Server
server.port=8080
